az-configuration:
- name: zone-1
  iaas_configuration_guid: ((director_az1_guid))
- name: zone-2
  iaas_configuration_guid: ((director_az2_guid))
- name: zone-3
  iaas_configuration_guid: ((director_az3_guid))
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: azure_alekssaul_com-virtual-network/azure_alekssaul_com-infrastructure-subnet
      cidr: 10.0.8.0/26
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.8.1
      reserved_ip_ranges: 10.0.8.1-10.0.8.9
      availability_zone_names:
      - "null"
  - name: pas
    subnets:
    - iaas_identifier: azure_alekssaul_com-virtual-network/azure_alekssaul_com-pas-subnet
      cidr: 10.0.0.0/22
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.0.1
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      availability_zone_names:
      - "null"
  - name: services
    subnets:
    - iaas_identifier: azure_alekssaul_com-virtual-network/azure_alekssaul_com-services-subnet
      cidr: 10.0.4.0/22
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.4.1
      reserved_ip_ranges: 10.0.4.1-10.0.4.9
      availability_zone_names:
      - "null"
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.google.com
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: true
    skip_director_drain: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: false
    trusted_certificates: |
      -----BEGIN CERTIFICATE-----
      MIIEwTCCAymgAwIBAgIQYDtvSfSZtJhm7+npCW7tTjANBgkqhkiG9w0BAQsFADB5
      MR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExJzAlBgNVBAsMHmFzYXVs
      QEFsZWtzcy1NYWNCb29rLVByby5sb2NhbDEuMCwGA1UEAwwlbWtjZXJ0IGFzYXVs
      QEFsZWtzcy1NYWNCb29rLVByby5sb2NhbDAeFw0xODA4MjIxNDUzMDJaFw0yODA4
      MjIxNDUzMDJaMHkxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTEnMCUG
      A1UECwweYXNhdWxAQWxla3NzLU1hY0Jvb2stUHJvLmxvY2FsMS4wLAYDVQQDDCVt
      a2NlcnQgYXNhdWxAQWxla3NzLU1hY0Jvb2stUHJvLmxvY2FsMIIBojANBgkqhkiG
      9w0BAQEFAAOCAY8AMIIBigKCAYEAvFngorJ1oYUkOwBgQwEDdcd5jg+LOjI5ekJH
      Eu1MWdvzo0Kdsw1lflxQF6dfVfTK2v6TgFfhLV7zXR965ACBxorAuFWD6UyuUE+m
      qPa71h23rKvm5wQvW0TJElPZldPr0+ru9eN072QafgzRLp+ef9w31TThonD7G8IZ
      KAeLUXnIJtuaUPGn2lG/YZk+t4AVfdBRcUoxj7LKucflMJsM2yR/mFZnnpsYCpe7
      QnR8LSsERIk1zh6uRjRfl6Ye6Ti1S1VuIePW0lppLK4G1vMFOGG5yfWbPBtzk4Wu
      6YnoDGg2248b3klWspgiQKrjX2mAmOPzmaNCXmDO0LU5sbHK7pJGMmPkq/tOEynh
      bdCOzHMliccXZ6JHZWONL+HVX7GHqRqPDGk0LFKCOWvReJDs7S4CuM/HJwfR0zhO
      /Jt6gIie2QAfNXM+NBwwoQKGL8QB/pKhfdr0O+ZTNiJub0P5KpNYGr38qNAK7h3e
      Yi6miBIhGJKcMnApEVTwmBNdlR6PAgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICBDAS
      BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBRe8GlUtUyP+ecqKC18BTnWxDC/
      TzANBgkqhkiG9w0BAQsFAAOCAYEAuybt2+HgofeaYhAXCG+lcwCAlJibLwH4NWlm
      F8fSy9S6aZnNZE/b7IhAsuPbWbXSqt8lt6Gql9mt4vxZ9MkA6vagn4qEh2FTqs1U
      EOMzFGmVMZpbF2L9xw1KblHodj/bHhvGXZNiU1LANFlPhRQSTbi1Y97Wir+qAPGa
      egwfntauFezBMzkzejj0FtC8uHPm9UZokkbnV7M+C4DF9XBbAvmTx7VEE8rq0UqZ
      EgWOu3FnsUVTRqvd9C0w0S5+0uLst1q4soyYH5pWr7FxvADRz8pPL/upleWJk9jW
      xPnloVVTCzpgbMpe9q4iUq25ctfYCcdDl58HEqywJ3v50RhlPZCXpbd8jAhsyXoy
      RptgG3YLTQxpv7kLzHMB8ixoqFSaFtyFWKM+idMOfJp7fg6mOPRq3JXmoB7kv/OY
      RkTRfCaw7ZPKmF+6ydCKQOTi2G5pLCU3oZ6XyNn3ivsQkXusDMcgNtMYxzL3e92V
      bJhAiy9/swqM1XvZAt2CIE4brtYZ
      -----END CERTIFICATE-----
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []