az-configuration:
- name: zone-1
  iaas_configuration_guid: ((director_az1_guid))
- name: zone-2
  iaas_configuration_guid: ((director_az2_guid))
- name: zone-3
  iaas_configuration_guid: ((director_az3_guid))
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: zone-1
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((director_vnet)))/azure_alekssaul_com-infrastructure-subnet
      cidr: 10.0.8.0/26
      reserved_ip_ranges: 10.0.8.1-10.0.8.9
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.8.1
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
  - name: pas
    subnets:
    - iaas_identifier: ((director_vnet)))/azure_alekssaul_com-pas-subnet
      cidr: 10.0.0.0/22
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.0.1
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
  - name: services
    subnets:
    - iaas_identifier: ((director_vnet)))/azure_alekssaul_com-services-subnet
      cidr: 10.0.4.0/22
      reserved_ip_ranges: 10.0.4.1-10.0.4.9
      dns: 168.63.129.16,8.8.8.8
      gateway: 10.0.4.1
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.google.com
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: true
    skip_director_drain: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  iaas_configuration:
    additional_cloud_properties: {}
    availability_mode: "availability_zones"
    bosh_storage_account_name: ((properties-configuration_iaas_configuration_bosh_storage_account_name))
    client_id: ((azure_client_id))
    client_secret: ((azure_client_secret))
    cloud_storage_type: ((properties-configuration_iaas_configuration_cloud_storage_type))
    default_security_group: ((properties-configuration_iaas_configuration_default_security_group))
    deployed_cloud_storage_type: ((properties-configuration_iaas_configuration_deployed_cloud_storage_type))
    deployments_storage_account_name: ((properties-configuration_iaas_configuration_deployments_storage_account_name))
    environment: "AzureCloud"
    guid: ((properties-configuration_iaas_configuration_guid))
    name: default
    resource_group_name: ((azure_resource_group))
    ssh_private_key: ((properties-configuration_iaas_configuration_ssh_private_key))
    ssh_public_key: ((properties-configuration_iaas_configuration_ssh_public_key))
    storage_account_type: ((properties-configuration_iaas_configuration_storage_account_type))
    subscription_id: ((properties-configuration_iaas_configuration_subscription_id))
    tenant_id: ((properties-configuration_iaas_configuration_tenant_id))
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: ((director_trusted_certificates))
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []